### ISSUE TITLE
Getting Question ID for Application Post

### ISSUE THREAD

**Issue by nickngqs** [grnhse/greenhouse-api-docs#116]
How do I get the question id for application post?

For greenhouse generated fields, I'm able to use the standard parameters like so first_name, last_name, etc.

But how do i get a specific question id?

I'm using the API method

For example in the docs
```
<label>LinkedIn Profile <input type="text" name="question_5555" /></label>
```

I'm assuming I shouldnt be using question_5555?

**Comment by felipeandres254** [comment]
Use job retrieve endpoint ([here](https://developers.greenhouse.io/job-board.html#retrieve-a-job)) with `?questions=true` to get the questions ID's
