### ISSUE TITLE
Is there an API to search a candidate id by their email?

### ISSUE THREAD

**Issue by bradvogel** [grnhse/greenhouse-api-docs#136]
Hi - I know this might be the right place to ask, but hoping for a quick answer :). Are there querystring parameters I can pass to https://developers.greenhouse.io/harvest.html#get-list-candidates to search for a candidate by their email address? Or is there a way I can use your handy https://app.greenhouse.io/people/search_bar api endpoint externally?

The use case is building a Greenhouse <-> Mixmax integration.

**Comment by richeyb** [comment]
Hi Brad! While we do not currently support the ability to search by email address in the API, we are currently researching adding such a feature. No word yet on timetable, as we would still need to prioritize this against other features and endpoints we currently have planned for the API.

I'll be happy to send you an update when we have more information on this feature! Thank you very much for your interest!

**Comment by bradvogel** [comment]
Thanks for the update. I'm in touch with Jillian and Garret over there to add this

**Comment by roymap** [comment]
Any update on this request?

**Comment by bradvogel** [comment]
Yes, this has been added. See the 'email' parameter of the List Candidates API: https://developers.greenhouse.io/harvest.html#get-list-candidates
