### ISSUE TITLE
Harvest API for adding interviewers to an interview

### ISSUE THREAD

**Issue by chellberg** [grnhse/greenhouse-api-docs#142]
Heya Greenhouse devs,

I'm working on some tooling to automate the interview scheduling process for our recruiter team, and I was specifically looking for an API for creating interviews for an application and adding interviewers to the interviews. Assuming I didn't miss those and they don't exist, are they on the roadmap?

Thanks so much,

Corin @ Braintree

**Comment by mmurph24** [comment]
Hi @chellberg! You didn't miss anything — it's only possible to view already-scheduled interviews, but we don't have a way to add them through the API right now. We haven't formally committed to this for the roadmap quite yet, but our Partnerships Team has been reaching out to potential scheduling integration partners to evaluate whether we should advocate for it in an upcoming quarter!
