### ISSUE TITLE
Filtering API endpoints

### ISSUE THREAD

**Issue by rickydunlop** [grnhse/greenhouse-api-docs#205]
Hi, there a couple of features we'd like to see in the API like filtering/sorting of endpoints and the inclusion of the candidate availability. 
Are there any plans to add these, is there a roadmap you could share?

**Comment by mmurph24** [comment]
@rickydunlop We're looking into the ability to filter the applications endpoint by status, but I believe that's the only major change we have planned around filtering and sorting right now. Adding availability to the API isn't a request something we've heard widely so far, but we can definitely keep that in mind for the future!
