### ISSUE TITLE
Question about candidate changes

### ISSUE THREAD

**Issue by jonasman** [grnhse/greenhouse-api-docs#209]
If the stage of an application changes what webhook is called?
`candidate_stage_change` or `application_updated` ?

**Comment by tdphillipsjr** [comment]
Hi Jonas. When an application is moved to another stage, it triggers a `candidate_stage_change` web hook. Application updated is more reserved for when information on the application changes like names or custom fields etc.

**Comment by jonasman** [comment]
thanks @tdphillipsjr , I think the documentation should mention this. Right now it is empty.
