### ISSUE TITLE
POST: Add Prospect returns 404

### ISSUE THREAD

**Issue by Ceasar** [grnhse/greenhouse-api-docs#214]
I am getting the following:

```
$ curl https://harvest.greenhouse.io/v1/prospects/ -u $API_KEY -X POST
{"message":"Resource not found"}
```

Is the documentation out of date? I expect an error, but not a 404.

I have checked my API key permissions and all are selected.

**Comment by Ceasar** [comment]
@tdphillipsjr

**Comment by Ceasar** [comment]
The issue I was having was that I was using my email address for "On-Behalf-Of" instead of my user ID. Is there a better way to get my user ID without a call to `/users`?

**Comment by tdphillipsjr** [comment]
Caeser - `/users?email=your@emailaddress.com` is the best way to get your account's user id through Harvest.
