### ISSUE TITLE
GET: List Sources does not return custom sources

### ISSUE THREAD

**Issue by Ceasar** [grnhse/greenhouse-api-docs#217]
Title. It only returns the defaults.

Is that intentional? I am working on an application where I would like to add a custom source to a candidate.

**Comment by Ceasar** [comment]
@tdphillipsjr, hope you're the right person to be tagging. :)

**Comment by mmurph24** [comment]
@Ceasar GET: List Sources will return both standard and custom sources, but the endpoint defaults to 100 per page. Right now we have ~165 standard sources, so if you don't use the `per_page` parameter to specify that you want additional sources, the custom sources wont show up. 

If you try something like https://harvest.greenhouse.io/v1/sources?per_page=500 instead, you should see the additional custom sources.
