### ISSUE TITLE
Way to find a school by name?

### ISSUE THREAD

**Issue by Ceasar** [grnhse/greenhouse-api-docs#222]
What is the intended way for a client to get the ID of a school? I have tried the following curl request::

```
curl \
  -u '$X' \
  -H 'On-Behalf-Of: $ID' \
  -v \
  https://harvest.greenhouse.io/v1/schools?name=harvard
```

But that filter had no effect.

Right now it seems like I either need to 1) page through the results until I find a match, or 2) download these into a database and write some simple search engine around it, but both of these seem impractical.

**Comment by mmurph24** [comment]
@Ceasar Right now we'd probably suggest one of the two workarounds you've highlighted. Adding a filter for school name is an interesting idea, though, and one that we can definitely consider adding eventually. Thanks for your input!

**Comment by hussainakbar10p** [comment]
Hi,
Which parameter can be used to fetch the next page? I tried page=2 and offset=2 but these didnt work.

The curl I am using:

> curl -X GET \
>   'https://harvest.greenhouse.io/v1/schools?offset=2' \
>   -H 'Accept: */*' \
>   -H 'Accept-Encoding: gzip, deflate' \
>   -H 'Authorization: $$' \
>   -H 'Cache-Control: no-cache' \
>   -H 'Connection: keep-alive' \
>   -H 'Host: harvest.greenhouse.io' \
>   -H 'User-Agent: PostmanRuntime/7.17.1' \
>   -H 'cache-control: no-cache'
