### ISSUE TITLE
Search job board

### ISSUE THREAD

**Issue by dardub** [grnhse/greenhouse-api-docs#242]
Looking through the greenhouse.io developer documentation, I don't see any parameters for a search query on the job board.

Are there any solutions for searching jobs with the current API?

**Comment by capablemonkey** [comment]
Hey @dardub,

There's no way to search/filter jobs in the Job Board API.  The [List Jobs](https://developers.greenhouse.io/job-board.html#list-jobs) endpoint will return all jobs.  You can filter that list on your end.

**Comment by dardub** [comment]
Thanks for prompt reply!
