### ISSUE TITLE
Candidate enter/exit stage info

### ISSUE THREAD

**Issue by tcn33** [grnhse/greenhouse-api-docs#244]
I'm not seeing a way to determine all the stages a candidate entered and exited, and the date/time for each - but Greenhouse displays this info. Is there an undocumented method for this?

**Comment by rachelleffel** [comment]
There is not a way to get that information using our API. I would recommend taking a look at our in-app reports, or using our Candidate Stage Change Web Hook to capture that information real-time: https://developers.greenhouse.io/webhooks.html#candidate-stage-change
