### ISSUE TITLE
Username highlight box for candidate notes doesn't scroll with text

### ISSUE THREAD

**Issue by niartenyaw** [grnhse/greenhouse-api-docs#260]
I know this doesn't belong on this repo, but I couldn't find another place to put it.

When tagging someone in the candidate `Make a Note` box, the highlight block doesn't scroll with the text:

<img width="336" alt="screen shot 2018-08-29 at 1 40 13 pm" src="https://user-images.githubusercontent.com/8084693/44814316-3275f900-ab91-11e8-8e3a-d30b113e15e6.png">

<img width="320" alt="screen shot 2018-08-29 at 1 40 20 pm" src="https://user-images.githubusercontent.com/8084693/44814324-386bda00-ab91-11e8-9fb0-6b5e7e9c9df3.png">

**Comment by mmurph24** [comment]
Hi @niartenyaw! Feel free to submit issues like this to our support team at support@greenhouse.io.
