### ISSUE TITLE
GET: List Jobs method has updated_before and updated_after parameters but the Job object has no obvious updated_at attribute.

### ISSUE THREAD

**Issue by DrMcTaco** [grnhse/greenhouse-api-docs#270]
When using the `GET: List Jobs` method you can specify to only return result updated before or after a timestamp. The objects returned do not have an attribute that corresponds to these parameters.
This makes validation and ordering by updating timestamp impossible.

**Comment by tdphillipsjr** [comment]
Hi Dan,

This is a good point. I added this to our backlog.

- Tom

**Comment by richeyb** [comment]
We've now added `updated_at` as one of the fields included on `GET: List Jobs`! 

For more information you can view our developer change log at https://developers.greenhouse.io/harvest.html#harvest-change-log! Thanks for bringing this to our attention!
