### ISSUE TITLE
Unable to query notes from rejection

### ISSUE THREAD

**Issue by colinsl** [grnhse/greenhouse-api-docs#274]
For applications that I view in the UI I can see the `notes` field populated under the rejection reason.
However when querying the application using `v1/applications/{id}` I do not see a `notes` field just a `decline_notes` field which is always empty. How can I recover the notes for the application rejection?

**Comment by mmurph24** [comment]
Hi @colinsl!

That information is simply saved as a note on the candidate's activity feed, so it would be available using `v1/candidates/{id}/activity_feed`. We may be able to investigate adding it to `v1/applications/{id}` at some point, but that work isn't planned at this time.
