### ISSUE TITLE
Webhook signature issue

### ISSUE THREAD

**Issue by 1nstinct** [grnhse/greenhouse-api-docs#276]
Hi, guys. 

I am developing endpoint for webhooks from your API. I encountered with incorrect signature header from you.
Ping request from you is generating correctly but _job_post_created_ webhook contains incorrectly processed signature header.

Ping webhook
body:
`{"action":"ping","payload":{"web_hook_id":4001693002,"endpoint_url":"https://67e09e60.ngrok.io/webhooks","created_at":"2018-12-20T15:43:12Z","updated_at":"2018-12-27T09:40:14Z","name":"Job Post Create","event":"Job Post Created","active":true,"content-type":"application/json"}}`
secret: 
`1uSUju2H6AohOE7OQVaxeLT3O8Uxxuas`
correctly processed signature on your and my side:
`395b1309fd37f0732d1ed11c15e03edd61b818918df6bf93be7c71bafb09c877`

**But**

job_post_created webhook
body:
`{"action":"job_post_updated","payload":{"id":4150486002,"title":"Manager","location":"Kharkov","content":"<p>test description 1111222</p>","internal_content":null,"updated_at":"2018-12-27T15:11:42.169Z","job_id":4144893002,"external":true,"internal":false,"live":true,"questions":[{"required":false,"private":false,"label":"LinkedIn Profile","type":"input_text","values":[]},{"required":false,"private":false,"label":"Website","type":"input_text","values":[]},{"required":false,"private":false,"label":"How did you hear about this job?","type":"input_text","values":[]},{"required":false,"private":false,"label":"Custom question #1","type":"textarea","values":[]},{"required":false,"private":false,"label":"Custom question #2","type":"textarea","values":[]}]}}`

secret the same:
`1uSUju2H6AohOE7OQVaxeLT3O8Uxxuas`

incorrect signature header from you is: `a4872b8a7ac7f187e5a9df4626145db590d80fc5c34fa837548e1d16f5b3ce93`

signature on my side is processing in the same way like for ping webhook: `a78444fa49e22f36f903ab7f1eea4de06675d3679037d67b115b2bf7f44b0a25`

According to your [documentation](https://developers.greenhouse.io/webhooks.html#authentication) signature should be computed as HMAC with secret. Different online tools show me that your computing is incorrect:
http://joxi.ru/DrlQ91WCV30p4m
You can check it by yourself [here](https://www.freeformatter.com/hmac-generator.html#ad-output)

Looking forward to receiving a help from you.

**Comment by capablemonkey** [comment]
Hi @1nstinct,

The `<` and `>` chars in the job post `content` field get unicode escaped when they are encoded as JSON.  For example, if the job post content is set to`<p>hello</p>`, the webhook body will represent it as `\u003cp\u003ehello\u003c/p\u003e`.

When we compute the signature, we use the string exactly as it appears in the body, including the escaped unicode.  

In other words, we use: 
`"content":"\u003cp\u003ehello\u003c/p\u003e",`

and not: 

`"content":"<p>hello</p>",`

So in your case, this is the string you should encode:

```
{"action":"job_post_updated","payload":{"id":4150486002,"title":"Manager","location":"Kharkov","content":"\u003cp\u003etest description 1111222\u003c/p\u003e","internal_content":null,"updated_at":"2018-12-27T15:11:42.169Z","job_id":4144893002,"external":true,"internal":false,"live":true,"questions":[{"required":false,"private":false,"label":"LinkedIn Profile","type":"input_text","values":[]},{"required":false,"private":false,"label":"Website","type":"input_text","values":[]},{"required":false,"private":false,"label":"How did you hear about this job?","type":"input_text","values":[]},{"required":false,"private":false,"label":"Custom question #1","type":"textarea","values":[]},{"required":false,"private":false,"label":"Custom question #2","type":"textarea","values":[]}]}}
```

Which produces the signature: 
`a4872b8a7ac7f187e5a9df4626145db590d80fc5c34fa837548e1d16f5b3ce93`

Hope that helps!

**Comment by 1nstinct** [comment]
@capablemonkey Thanks a lot. It works fine! BTW may be there is a sense to add one sentence to documentation and mention about this feature?

**Comment by tdphillipsjr** [comment]
This has been resolved.

**Comment by rabbitt** [comment]
I'm a bit late to this but, can you provide a python example that properly performs signature verification. I can't for the life of me figure out how your doing it. I'm more or less doing this in an AWS Lambda function which is hooked into an AWS API Gateway that I have your webhooks coming into:

```python
import hmac, hashlib, json

ses = boto3.session.Session().client(service_name='secretsmanager')
SECRET = ses.get_secret_value(SecretId='secret_key')['SecretString'].encode()

def generate_hmac(body):
  return hmac.new(SECRET, body.encode('unicode-escape'), hashlib.sha256).hexdigest()

def lambda_handler(event, context):
  body = json.loads(event['body'])
  signature = event['headers']['Signature'].split(' ')[1]

  if signature != generate_hmac(body):
    return { 'statusCode': 403, "Not Permitted" } 
```
This never seems to generate the correct HMAC to match what you present in the `Signature` header. Maybe you could add some examples in your website for various languages?

**Comment by nicosommi** [comment]
Hi! Adding my two cents here

It would be great if you use an encoding that is supported by Node.js or to provide a snippet for it as well in addition to Ruby and PHP.

Also, it would be nice to include a sample of these characters when creating the webhook, which is kind of a "validation step".

Finally, a generic snippet for the replacements on the section "Important note on Unicode" would be great too if changing the encoding is not an option.

These two will make the developer experience much better.

My experience was: created webhooks successfully on local tests, and then fails when running it with HTML on the payload. Then I add just the replacement on the content for the Job Post, and I still can't compute the signature to the proper one.

**Comment by nicosommi** [comment]
Contentful has a nice experience for this, they [provide a library](https://github.com/contentful/node-apps-toolkit/blob/master/src/requests/verify-request.ts#L59-L87)

**Comment by TanmayNikam** [comment]
> @capablemonkey Thanks a lot. It works fine! BTW may be there is a sense to add this feature to the documentation?

how did you get the unicode escaped string

**Comment by prachi-sequoia** [comment]
Hi, can anyone help me as to how we could get the unicode escaped string? For the same scenario in my request body payload I receive the data like this one:
`"content":"<p>hello</p>"`

How can we update it to `"content":"\u003cp\u003ehello\u003c/p\u003e"` ?

**Comment by TanmayNikam** [comment]
@nicosommi how did you get the unicode escape sequence in node.js, I tried with encodeURIComponent but the hash mismatches

**Comment by gat786** [comment]
@capablemonkey can I get like a python code using which I can calculate this webhooks signature? I have been trying to calculate it for days and have not succeeded yet.

**Comment by silawrenc** [comment]
Hey all, we've been battling with this one from a nodejs perspective, but I think some of our findings apply to python too. I think the root of the problem is the different ways that languages handle strings so you have:

**php**
```php
<?php
echo '\u003cp\u003ehello\u003c/p\u003e' === '<p>hello</p>'; // false, unicode escapes aren't automatically converted on string instantiation
?>
```

**ruby**
```rb
# Ruby, also false same reason
puts '\u003cp\u003ehello\u003c/p\u003e' === '<p>hello</p>'
```

**node**
```js
// node, this returns true but as buffers would be different
console.log('\u003cp\u003ehello\u003c/p\u003e' === '<p>hello</p>')
```

**python**
```py
# python behaves same as node, also true
print('\u003cp\u003ehello\u003c/p\u003e' == '<p>hello</p>')
```


Essentially unicode escapes are preserved as-is in ruby and php strings, whereas in python and node they are converted on string instantiation to their equivalent characters. Thus in php and ruby, it doesn't matter whether you convert the request body into a string, or work with it in its byte form (e.g. a buffer in nodejs), you get the same result. Whereas if you work with the request body as a string (including as JSON) in node or python, you have to reverse-engineer all the escape sequences that were applied by greenhouse. Now we've contacted greenhouse support and they weren't able to give either a reason for applying those escapes, or an exhaustive list of the characters that might be escaped. However, if we calculated the signature from the byte representation of the request body, without ever parsing it into a string or JSON, then we could calculate a matching signature.

I hope this is helpful for some folks!

**Comment by puntubabu** [comment]
@silawrenc Thanks for the explanation!
I'm using Node v16 and still having some trouble getting signatures to match.

I got the byte representation and hashed the body like so:
``` javascript
// const signature = derived from header
const byteBody = req.rawBody;
const signatureHash = crypto
    .createHmac('sha256', Buffer.from(superSecretWebhookKey 'hex'))
    .update(byteBody)
    .digest('hex');
    
 const areTheyEqual = (signature === signatureHash) // false   
``` 

But the signature and `signatureHash` don't match.

Am I missing a step here?

Thanks

**Comment by maxsye** [comment]
[silawrenc](https://github.com/silawrenc) Thank you for for comment. I've been trying to get this webhook signature to work for ages. What did you use to calculate the signature from the byte representation of the request body, without ever parsing it into a string or JSON? I'm using Node btw.
