### ISSUE TITLE
<Job Board API> No clear relationship between `location` and `offices`

### ISSUE THREAD

**Issue by bcarradini** [grnhse/greenhouse-api-docs#278]
In the example response provided at [https://developers.greenhouse.io/job-board.html#list-jobs](https://developers.greenhouse.io/job-board.html#list-jobs) there's no clear relationship between the `location` specified for the job and the `offices` specified for job. And it doesn't appear that `offices` is simply a list of all offices associated with the employer, because I've found at least one example where the response to `GET /v1/boards/<token>/offices` contains more offices than those listed in the response to `GET /v1/boards/<token>/jobs`.

The documentation needs to be clarified. Specifically:
- How exactly should `job['offices']` be interpreted?
- Is there any enforced relationship at all between `job['location']` and `job['offices']` or are both sets of data totally free-form and at the whim of whoever posted the job?

**Comment by tdphillipsjr** [comment]
Hi Barbara,

The offices contained in a job object are a subset of the offices contained at the offices endpoint. They are the offices users have explicitly selected to associate with the given job. So, for instance, all jobs for the "New York" office might have only one entry in their office list for the "New York" offices, while the offices endpoint would list all offices the company has; "New York," "Boston," etc.

The office list bears no relationship to the "location" element. The location element is a free form bit of text the user can enter on the job in addition to the job post. So, while "office" could be set to "New York," location could be set to something like "9th Floor" or "Lexington Ave."

If you'd like to submit an update to the documentation that you think would help clarify this information, we'd be happy to have a look. Thanks!
