### ISSUE TITLE
[Harvest API] Is OAuth2 on the roadmap?

### ISSUE THREAD

**Issue by aguynamedben** [grnhse/greenhouse-api-docs#299]
Hi, it's awesome y'all are active on here! 👏

I'm just curious if OAuth2 support is on the roadmap for the Harvest API. My Greenhouse integration would be much easier to use if the end users could OAuth with their Greenhouse account... vs. having to dig through Dev Center settings to create and copy an API Key.

I know this kind of stuff can be difficult to migrate to, but I was just curious!

**Comment by aguynamedben** [comment]
N/m, looks like this isn't on the roadmap.

**Comment by MoSattler** [comment]
same for me! Right now integration is really cumbersome
