### ISSUE TITLE
Add Note to Candidate throws Access Denied

### ISSUE THREAD

**Issue by selvavalluvan** [grnhse/greenhouse-api-docs#393]
I was using the API key to add notes to activity feed. The API key works for certain greenhouse users when i use those user_id in on-behalf-of header. If i use a different user_id it throws Access Denied error.

I assume this is Permission related but i can't figure out what those are. Could you guys please explain?

Thanks

https://harvest.greenhouse.io/v1/candidates/********/activity_feed/notes
-H "Content-Type: application/json"
-H "On-Behalf-Of: {greenhouse user ID}"
-H "Authorization: Basic ****"
{
  "user_id": {greenhouse user ID},
  "body": "Test message",
  "visibility": "public"
}

**Comment by alienatix** [comment]
I have the same problem, getting error:

`{
    "errors": [
        {
            "message": "Not found"
        }
    ]
}`
