### ISSUE TITLE
ASK : Is it possible to add my university name into school list?

### ISSUE THREAD

**Issue by aratnamirasugab** [grnhse/greenhouse-api-docs#434]
Hi guys, before that I would like to say thank you to guys engineers who worked on this greenhouse API.

So the problem is I wanted to apply to a Software Engineer role in one of tech companies, their job board require me to input my university name, but couldn't find it. Is it possible to add it into the list? currenltly I am reading the docs but couldn't find the way to input to the list. Thanks guys!

**Comment by jsurrett** [comment]
Sorry for the late response. We are now more closely monitoring this space. The list of universities would need to be updated by the company that has the job board. That is something that they can do as part of the Greenhouse user interface and not through the APIs.

**Comment by micmalti** [comment]
Ok, but it seems like the tyranny of the default is at play here, in the sense that by having a restrictive list set as the default, practically all job boards are excluding the same universities. Why can't the default list be non-restrictive? It's frustrating to see your alma mater being excluded, despite being ranked higher than some of the universities listed.
