### ISSUE TITLE
Is it possible to delete prospect applications using Harvest API?

### ISSUE THREAD

**Issue by meh9184** [grnhse/greenhouse-api-docs#442]
Hello, thanks for making a nice api.

I want to batch delete applications created in the prospect pool using Harvest api, (in order to post-process the applications created incorrectly on the server 😭 )

But looking at the api documentation, it is possible to delete applications but not prospect. 

<img src="https://user-images.githubusercontent.com/8400686/134280994-bafe0ef0-8e78-4339-bf5c-86777f0934dc.png" width="70%" />

If I have permission to delete prospects, I am wondering if there is a way to batch delete all or by using the api.

Thank you for always working hard!

**Comment by meh9184** [comment]
@tdphillipsjr Excuse, have worked on this recently, so let's mention..! 🙏

**Comment by noralin** [comment]
Hi @meh9184, our Harvest API does not support deleting a prospect currently. 

Please feel free to reach out to the Greenhouse point person in your company so they can relay this product request/feedback to the Greenhouse product team, thanks!
