### ISSUE TITLE
Introduction should explain how to get API key

### ISSUE THREAD

**Issue by dbu** [grnhse/greenhouse-api-docs#61]
The introduction should explain how to get an API key (or link to the corresponding documentation). I am quite lost looking at the beginning of the introduction.

Also, because i was logged into greenhouse while reading the doc, i first expected to be able to copy-paste the example `curl https://harvest.greenhouse.io/v1/candidates/ -u a7183e1b7e9ab09b8a5cfa87d1934c3c:` but now found that this is just a hardcoded example. There should be some comment in the example that i need to replace this with my API key. Or do `curl https://harvest.greenhouse.io/v1/candidates/ -u [your api key]:` to make it more clear...

**Comment by yanismydj** [comment]
Same issue here, can't find my API key anywhere!

**Comment by dbu** [comment]
greenhouse support told me:

I reviewed your profile and see that you do not have the user permissions enabled to access your company system's dev center to create an API token. 

I recommend reaching out to a site admin on your team who has the ability edit user permissions, to enable the developer permissions on your user profile. Once you have developer permissions, you should be able to access you api key via Configure > Dev Center > API Credential Management.

i guess it would be useful if that was somewhere in the documentation, and linked from the start of the introduction. as in: find your key there. if there is no key there, you probably don't have the right permissions...

**Comment by acreeger** [comment]
@dbu, we couldn't agree more. We'll add some more info to the documentation ASAP. Thanks!

**Comment by tdphillipsjr** [comment]
Resolved: https://github.com/grnhse/greenhouse-api-docs/pull/113
