### ISSUE TITLE
Add Prospect to a job.

### ISSUE THREAD

**Issue by joshuakarjala** [grnhse/greenhouse-api-docs#73]
When creating a new prospect I was expecting to be able to submit an Application object with a `job_id` so that the prospect was mapped to specific jobs.

Right now this is not possible - it works when adding a candidate.

**Comment by tdphillipsjr** [comment]
This currently is wrong in the documentation.  You can do this in a slightly different way for prospects.  In the POST prospect endpoint, the element is `application` which takes an array of `job_ids`

So in the request you'd add `"application": { "job_ids": [12,34,56] }`

We'll update the documentation to reflect this.  Thanks for pointing this out.

**Comment by tdphillipsjr** [comment]
Resolved: https://github.com/grnhse/greenhouse-api-docs/pull/112
