### ISSUE TITLE
Add "location" property to "POST: Create candidate" endpoint

### ISSUE THREAD

**Issue by sp-eric-pinto** [grnhse/greenhouse-api-docs#99]
Right now the "location" property for candidates is only accessible from the web interface.

![image](https://cloud.githubusercontent.com/assets/16895475/25007114/912b4284-205f-11e7-919c-467153b44f91.png)

It would be nice to have it in the API endpoint so we can improve our time spent in just accessing the web interface and modifying this field.

Thanks in advance.

**Comment by mmurph24** [comment]
I've added this to the list of API/Web Hook feature requests for the team to consider moving forward. Thanks so much for the input!

**Comment by Ceasar** [comment]
+1
